### PR TITLE
Fix typo in messages.json

### PR DESCRIPTION
**Pull request by sebdiem**

### CODE REVIEW

**Comment by danny0838** [comment]
Thank you. Can you revise the commit message to fit the general styling convention? Such as:

    ui: fix typo in messages.json for en

**Comment by sebdiem** [comment]
done !

**Comment by danny0838** [comment]
Another problem, please revise the commit to exclude the change of EOL.

**Comment by sebdiem** [comment]
updated, sorry for the useless round-trip

**Pull request merged**
